server:
  port: 9093
spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://CRUXx:Crux%4011@cluster0.zuegb.mongodb.net/Orders?retryWrites=true&w=majority
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    path: C:/Users/Shriganesh/Desktop/logs/order.log

