spring:
  data:
    mongodb:
      uri: mongodb+srv://CRUXx:Crux%4011@cluster0.zuegb.mongodb.net/Orders?retryWrites=true&w=majority
  application:
    name: PAYMENT-SERVICE

server:
  port: 9093
logging:
  file:
    path: C:/Users/Shriganesh/Desktop/logs/payment.log