spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CRUXx11/cloud-config-server
          username: CRUXx11
          password: Crux%4011
          default-label: main
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
server:
  port: 9088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    name: localhost


