server:
  port: 9094
spring:
  application:
    name: PAYMENT-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://CRUXx:Crux%4011@cluster0.zuegb.mongodb.net/Orders?retryWrites=true&w=majority

logging:
  file:
    path: C:/Users/Shriganesh/Desktop/logs/payment.log