server:
  port: 9094
spring:
  application:
    name: PAYMENT-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://CRUXx:Crux%4011@cluster0.zuegb.mongodb.net/Orders?retryWrites=true&w=majority

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
